import {
  AccountBalanceOutlined,
  MonetizationOnOutlined,
  ShoppingBagOutlined,
  StoreOutlined,
} from "@mui/icons-material";
import PersonOutlineOutlinedIcon from "@mui/icons-material/PersonOutlineOutlined";
import ViewQuiltRoundedIcon from "@mui/icons-material/ViewQuiltRounded";
import MailOutlinedIcon from "@mui/icons-material/MailOutlined";
import PendingActionsOutlinedIcon from "@mui/icons-material/PendingActionsOutlined";
import FavoriteBorderOutlinedIcon from "@mui/icons-material/FavoriteBorderOutlined";
import PermIdentityOutlinedIcon from "@mui/icons-material/PermIdentityOutlined";

export const navLinks = [
  {
    label: "Home",
    link: "/",
  },
  {
    label: "About",
    link: "/about",
  },
  {
    label: "Contact",
    link: "/contact",
  },
  {
    label: "SignUp",
    link: "/signup",
  },
];

export const analytics = [
  {
    icon: <StoreOutlined />,
    number: "10.5k",
    title: "Sallers active in our site",
  },
  {
    icon: <MonetizationOnOutlined />,
    number: "33k",
    title: "Monthly product sale",
  },
  {
    icon: <ShoppingBagOutlined />,
    number: "45.5k",
    title: "Customers active in our site",
  },
  {
    icon: <AccountBalanceOutlined />,
    number: "25.5k",
    title: "Annual gross sale in our site",
  },
];

export const founders = [
  {
    image: "/images/tom-cruise.png",
    role: "Founder & Chairman",
    name: "Tom Cruise",
    twitterLink: "#",
    instagramLink: "#",
    LinkedInLink: "#",
  },
  {
    image: "/images/emma-watson.png",
    role: "Managing Director",
    name: "Emma Watson",
    twitterLink: "#",
    instagramLink: "#",
    LinkedInLink: "#",
  },
  {
    image: "/images/will-smith.png",
    role: "Product Designer",
    name: "Will Smith",
    twitterLink: "#",
    instagramLink: "#",
    LinkedInLink: "#",
  },
];

export const hero = [
  {
    image: "/images/hero-frame-1.png",
    text: "Up to 10%  off Voucher",
    name: "iPhone 14 series",
    tinyImage: "/images/apple-gray-logo.png",
  },
  {
    image: "/images/boomblox.png",
    text: "Up to 20%  off Voucher",
    name: "BoomBlox series",
    tinyImage: "/images/boomblox.png",
  },
  {
    image: "/images/ps5-play-station.png",
    text: "Up to 15%  off Voucher",
    name: "Play Station 5",
    tinyImage: "/images/ps5-play-station.png",
  },
];

export const productsData = [
  {
    id: 1,
    name: "Amazon Echo",
    image: "/images/amazon-echo.png",
    category: "Electronics",
    categoryType: "Flash sales",
    isNew: false,
    inStock: true,
    numberOfProducts: 25,
    price: 99.99,
    ratings: 4.5,
    discountPercentage: 20,
    newPrice: 79.99,
    description:
      "Experience the latest in smart home technology with the Amazon Echo. Stream music, control your smart devices, and more.",
  },
  {
    id: 2,
    name: "Boomblox",
    image: "/images/boomblox.png",
    category: "Electronics",
    categoryType: "Flash sales",
    isNew: true,
    numberOfProducts: 20,
    price: 129.99,
    ratings: 4.8,
    discountPercentage: 10,
    newPrice: 116.99,
    description:
      "Get ready to elevate your audio experience with the Boomblox. Crisp sound and stylish design for music lovers.",
    inStock: false,
  },
  {
    id: 3,
    name: "Canon Camera",
    image: "/images/canon-camera.png",
    category: "Electronics",
    categoryType: "Best selling products",
    isNew: true,
    numberOfProducts: 15,
    price: 299.99,
    ratings: 2.7,
    discountPercentage: 15,
    newPrice: 254.99,
    description:
      "Capture life's moments in stunning detail with the Canon Camera. Perfect for photography enthusiasts.",
    inStock: true,
  },
  {
    id: 4,
    name: "Keyboard",
    image: "/images/keyboard.png",
    category: "Electronics",
    categoryType: "Best selling products",
    isNew: false,
    numberOfProducts: 30,
    price: 79.99,
    ratings: 4.6,
    discountPercentage: 10,
    newPrice: 71.99,
    description:
      "Enhance your typing experience with this high-quality keyboard. Ideal for work and gaming.",
    inStock: false,
  },
  {
    id: 5,
    name: "LCD Monitor",
    image: "/images/lcd-monitor.png",
    category: "Electronics",
    categoryType: "Flash sales",
    isNew: true,
    numberOfProducts: 10,
    price: 199.99,
    ratings: 4.9,
    discountPercentage: 15,
    newPrice: 169.99,
    description:
      "Upgrade your display with the LCD Monitor. Crystal-clear visuals for work and entertainment.",
    inStock: true,
  },
  {
    id: 6,
    name: "Gamepad Red",
    image: "/images/game-pad-red.png",
    category: "Gaming",
    categoryType: "Flash sales",
    isNew: false,
    numberOfProducts: 50,
    price: 39.99,
    ratings: 4.7,
    discountPercentage: 15,
    newPrice: 33.99,
    description:
      "Elevate your gaming experience with the Gamepad Red. Precision control for competitive gaming.",
    inStock: true,
  },
  {
    id: 7,
    name: "White Gamepad",
    image: "/images/white-gamepad.png",
    category: "Gaming",
    categoryType: "Flash sales",
    isNew: false,
    numberOfProducts: 40,
    price: 49.99,
    ratings: 3.9,
    discountPercentage: 20,
    newPrice: 39.99,
    description: `PlayStation 5 Controller Skin High quality vinyl with air channel
    adhesive for easy bubble free install & mess free removal pressure
    sensitive`,
    inStock: true,
  },
  {
    id: 8,
    name: "Gaming Laptop",
    image: "/images/gaming-laptop.png",
    category: "Gaming",
    categoryType: "Best selling products",
    isNew: false,
    numberOfProducts: 30,
    price: 999.99,
    ratings: 2.5,
    discountPercentage: 10,
    newPrice: 899.99,
    description:
      "Experience gaming like never before with the Gaming Laptop. Powerful performance for demanding games.",
    inStock: false,
  },
  {
    id: 9,
    name: "PS5 Play Station",
    image: "/images/ps5-play-station.png",
    category: "Gaming",
    categoryType: "Best selling products",
    isNew: false,
    numberOfProducts: 20,
    price: 499.99,
    ratings: 5.0,
    discountPercentage: 0,
    newPrice: 499.99,
    description:
      "Join the next generation of gaming with the PS5 Play Station. Immersive gameplay and stunning graphics.",
    inStock: true,
  },
  {
    id: 10,
    name: "CPU Cooler",
    image: "/images/cpu-cooler.png",
    category: "Gaming",
    categoryType: "Flash sales",
    isNew: false,
    numberOfProducts: 35,
    price: 49.99,
    ratings: 4.3,
    discountPercentage: 25,
    newPrice: 37.49,
    description:
      "Keep your gaming rig cool with the CPU Cooler. Efficient cooling for optimal performance.",
    inStock: false,
  },
  {
    id: 11,
    name: "Book Shelf",
    image: "/images/book-shelf.png",
    category: "Furnitures",
    categoryType: "Flash sales",
    isNew: false,
    numberOfProducts: 45,
    price: 129.99,
    ratings: 4.8,
    discountPercentage: 10,
    newPrice: 116.99,
    description:
      "Add style and functionality to your home with the Book Shelf. Store and display your favorite books and decor.",
    inStock: true,
  },
  {
    id: 12,
    name: "Comfort Chair",
    image: "/images/comfort-chair.png",
    category: "Furnitures",
    categoryType: "Flash sales",
    isNew: true,
    numberOfProducts: 30,
    price: 149.99,
    ratings: 2.7,
    discountPercentage: 20,
    newPrice: 119.99,
    description:
      "Relax in ultimate comfort with the Comfort Chair. Stylish and ergonomic design for your living space.",
    inStock: false,
  },
  {
    id: 13,
    name: "Boomblox",
    image: "/images/boomblox.png",
    category: "Furnitures",
    categoryType: "Best selling products",
    isNew: false,
    numberOfProducts: 60,
    price: 39.99,
    ratings: 4.0,
    discountPercentage: 0,
    newPrice: 39.99,
    description:
      "Create a modern and chic atmosphere with Boomblox. Versatile and affordable furniture for your home.",
    inStock: true,
  },
  {
    id: 14,
    name: "Curology Product",
    image: "/images/curology-product.png",
    category: "Furnitures",
    categoryType: "Best selling products",
    isNew: true,
    numberOfProducts: 20,
    price: 79.99,
    ratings: 4.5,
    discountPercentage: 15,
    newPrice: 67.99,
    description:
      "Experience the magic of Curology Products. Enhance your skincare routine with high-quality products.",
    inStock: false,
  },
  {
    id: 15,
    name: "Gucci Bag",
    image: "/images/gucci-bag.png",
    category: "Men's fashion",
    categoryType: "Flash sales",
    isNew: true,
    numberOfProducts: 50,
    price: 299.99,
    ratings: 2.9,
    discountPercentage: 10,
    newPrice: 269.99,
    description:
      "Upgrade your style with the Gucci Bag. A symbol of luxury and sophistication for fashion-forward individuals.",
    inStock: true,
  },
  {
    id: 16,
    name: "Satin Jacket",
    image: "/images/satin-jacket.png",
    category: "Men's fashion",
    categoryType: "Flash sales",
    isNew: false,
    numberOfProducts: 40,
    price: 119.99,
    ratings: 4.7,
    discountPercentage: 0,
    newPrice: 119.99,
    description:
      "Stay stylish and comfortable with the Satin Jacket. Perfect for a casual yet trendy look.",
    inStock: false,
  },
  {
    id: 17,
    name: "Book Shelf",
    image: "/images/book-shelf.png",
    category: "Women's fashion",
    categoryType: "Flash sales",
    isNew: false,
    numberOfProducts: 60,
    price: 249.99,
    ratings: 3.8,
    discountPercentage: 30,
    newPrice: 174.99,
    description:
      "Organize your fashion essentials with the Book Shelf. Chic storage solution for your wardrobe.",
    inStock: true,
  },
  {
    id: 18,
    name: "Perfume Gucci",
    image: "/images/perfume-gucci.png",
    category: "Women's fashion",
    categoryType: "Best selling products",
    isNew: true,
    numberOfProducts: 45,
    price: 39.99,
    ratings: 4.5,
    discountPercentage: 0,
    newPrice: 39.99,
    description:
      "Elevate your scent game with Perfume Gucci. A captivating fragrance for the modern woman.",
    inStock: true,
  },
  {
    id: 19,
    name: "Breed Dry Dog Food",
    image: "/images/dry-dog-food.png",
    category: "Pets",
    categoryType: "Best selling products",
    isNew: true,
    numberOfProducts: 45,
    price: 39.99,
    ratings: 4.5,
    discountPercentage: 0,
    newPrice: 39.99,
    description:
      "Nourish your furry friend with Breed Dry Dog Food. High-quality nutrition for a healthy and happy pet.",
    inStock: true,
  },
];

export const accountMenus = [
  {
    name: "My Exclusive Account",
    icon: <PersonOutlineOutlinedIcon />,
    order: 1,
    link: "/customer/account",
  },
  {
    name: "Orders",
    icon: <ViewQuiltRoundedIcon />,
    order: 2,
    link: "/customer/orders",
  },
  {
    name: "Inbox",
    icon: <MailOutlinedIcon />,
    order: 3,
    link: "/customer/inbox",
  },
  {
    name: "Pending Reviews",
    icon: <PendingActionsOutlinedIcon />,
    order: 4,
    link: "/customer/pending-review",
  },
  {
    name: "Saved Items",
    icon: <FavoriteBorderOutlinedIcon />,
    order: 5,
    link: "/customer/wishlist",
  },
];

export const accountDropdown = [
  {
    name: "My Account",
    icon: <PermIdentityOutlinedIcon />,
    link: "/customer/orders",
  },
  {
    name: "Orders",
    icon: <ViewQuiltRoundedIcon />,
    link: "/customer/orders",
  },
  {
    name: "Inbox",
    icon: <MailOutlinedIcon />,
    link: "/customer/inbox",
  },
  {
    name: "Pending Reviews",
    icon: <PendingActionsOutlinedIcon />,
    link: "/customer/pending-review",
  },
  {
    name: "Saved Items",
    icon: <FavoriteBorderOutlinedIcon />,
    link: "/customer/wishlist",
  },
];
