import "./globals.css";
import { Inter } from "next/font/google";

// components
import { ContextProvider } from "./context/AppContext";
import Navbar from "./components/Navbar";
import Footer from "./components/footer/Footer";
import BottomNavbar from "./components/BottomNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Navbar />
          {children}
        </ContextProvider>
        <BottomNavbar />
        <Footer />
      </body>
    </html>
  );
}
